# .circleci/config.yml

version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2004:202107-01

    steps:
      - checkout

      # Install dependencies and create virtual environment
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt install -y sshpass 
      
      # Deploy the application
      - run:
          name: Setup and move the project
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} 'sudo apt-get -y update && sudo apt install -y python3-pip python3-dev libpq-dev postgresql postgresql-contrib nginx curl python3.10-venv'
            sshpass -p "${SSH_PASSWORD}" rsync -r . ${SSH_USERNAME}@${SERVER_IP}:/home/${PROJECT_FOLDER}

      # Deploy the application
      - run:
          name: Set env and migrate DB
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && python3 -m venv venv"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && source venv/bin/activate && pip install -r requirements.txt"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}' >> .env"

            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'SECRET_KEY=${SECRET_KEY}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'CLOUD_NAME=${CLOUD_NAME}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'CLOUD_API_KEY=${CLOUD_API_KEY}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'CLOUD_API_SECRET=${CLOUD_API_SECRET}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'ALLOWED_HOSTS=${ALLOWED_HOSTS}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'ENVIRONMENT=${ENVIRONMENT}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'email_key=${email_key}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'vonage_api_key=${vonage_api_key}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'vonage_api_secret=${vonage_api_secret}' >> .env"
  
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && echo 'GEO_API_KEY=${GEO_API_KEY}' >> .env"
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && source venv/bin/activate && python manage.py migrate"
      
      
      - run:
          name: Setup Gunicorn
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && chmod +x scripts/gunicorn_sock.sh && scripts/gunicorn_sock.sh"

            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && chmod +x scripts/gunicorn_service.sh && scripts/gunicorn_service.sh ${PROJECT_FOLDER}"

      - run:
          name: Setup Nginx
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && chmod +x scripts/nginx_setup.sh && scripts/nginx_setup.sh ${SERVER_IP} ${PROJECT_FOLDER}"

  setup_db:
    machine:
      image: ubuntu-2004:202107-01

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt install -y sshpass 

      - run:
          name: Install PostgreSQL
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} 'sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib'
      
      - run:
          name: Start PostgreSQL service
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} 'sudo service postgresql start && sudo systemctl enable postgresql'
      - run:
          name: Create PostgreSQL database
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"CREATE DATABASE ${DB_NAME};\""


      - run:
          name: Create PostgreSQL USER
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';\""

      - run:
          name: Update PostgreSQL USER Role
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"ALTER ROLE ${DB_USER} SET client_encoding TO 'utf8';\""

      - run:
          name: Set PostgreSQL USER Role
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"ALTER ROLE ${DB_USER} SET default_transaction_isolation TO 'read committed';\""
      
      - run:
          name: Update PostgreSQL USER Role TIMEZONE
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"ALTER ROLE ${DB_USER} SET timezone TO 'UTC';\""
      
      - run:
          name: Grant PostgreSQL USER privileges
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "sudo -u postgres psql -c \"GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};\""


  update_deploy:
    machine:
      image: ubuntu-2004:202107-01

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt install -y sshpass 

      - run:
          name: Move the project to remote server
          command: |
            sshpass -p "${SSH_PASSWORD}" rsync -r . ${SSH_USERNAME}@${SERVER_IP}:/home/${PROJECT_FOLDER}

      - run:
          name: Migrate DB
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && source venv/bin/activate && python manage.py migrate"

      - run:
          name: Restart Services
          command: |
            sshpass -p "${SSH_PASSWORD}" ssh ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && chmod +x scripts/restart_services.sh && scripts/restart_services.sh"

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - setup_db:
      #     filters:
      #       branches:
      #         only:
      #           - production  
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - production  
      #     requires:
      #       - setup_db

      - update_deploy:
          filters:
            branches:
                only:
                  - staging