# Generated by Django 4.2 on 2023-05-09 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='contact_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
