# Generated by Django 4.2 on 2023-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisations_contact_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
