# Generated by Django 4.2 on 2023-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organisations_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=300, null=True, verbose_name='state'),
        ),
    ]
