# Generated by Django 4.2 on 2023-05-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_status_notifications_message_and_more'),
        ('accounts', '0007_remove_user_category_remove_user_open_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
