# Generated by Django 4.2 on 2023-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organisations_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
