# Generated by Django 4.2 on 2023-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_password',
            field=models.CharField(max_length=100, null=True, verbose_name='open_password'),
        ),
    ]
