# Generated by Django 4.2 on 2023-05-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_open_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.CharField(max_length=300, null=True, verbose_name='organisation'),
        ),
    ]
