# Generated by Django 4.2 on 2023-04-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panicrequest',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='panicrequest',
            name='long_lat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trackmerequest',
            name='long_lat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
