# Generated by Django 4.2 on 2023-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_panicrequest_location_panicrequest_long_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panicrequest',
            old_name='long_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='trackmerequest',
            old_name='long_lat',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='panicrequest',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trackmerequest',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
