# Generated by Django 4.2 on 2023-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_callrequest_organisation_images_organisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflocation',
            old_name='address',
            new_name='city',
        ),
    ]
