# Generated by Django 4.2 on 2023-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='panicrequest',
            name='is_genuine',
            field=models.BooleanField(default=True),
        ),
    ]
