# Generated by Django 4.2 on 2023-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_long_lat_panicrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panicrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackmerequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
