# Generated by Django 4.2 on 2023-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_panicrequest_is_genuine'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
