# Generated by Django 4.2 on 2023-05-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflocation',
            name='country',
        ),
    ]
