# Generated by Django 4.2 on 2023-05-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='panicrequest',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
