# Generated by Django 4.2 on 2023-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_stafflocation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(null=True, upload_to='capture'),
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(null=True, upload_to='capture'),
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(null=True, upload_to='capture'),
        ),
    ]
