# Generated by Django 4.2 on 2023-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_emergencycontact_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
