# Generated by Django 4.2 on 2023-05-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_emergencycontact_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image4',
        ),
    ]
