# Generated by Django 4.2 on 2023-05-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_category_remove_user_open_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_images_image2_remove_images_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='status',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='panicrequest',
            old_name='state',
            new_name='user_location',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stafflocation',
            name='user',
        ),
        migrations.AddField(
            model_name='stafflocation',
            name='user_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_notifications', to='accounts.organisations'),
        ),
    ]
