# Generated by Django 4.2 on 2023-05-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organisations_name'),
        ('main', '0013_rename_status_notifications_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflocation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
    ]
