# Generated by Django 4.2 on 2023-05-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organisations_name'),
        ('main', '0014_alter_stafflocation_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflocation',
            old_name='user_location',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='stafflocation',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
    ]
