# Generated by Django 4.2 on 2023-05-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organisations_name'),
        ('main', '0015_rename_user_location_stafflocation_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
        migrations.AlterField(
            model_name='panicrequest',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
        migrations.AlterField(
            model_name='trackmerequest',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organisations'),
        ),
    ]
